[package]
name = "supervisor"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
postgres = { version = "0.19", default-features = false }
postgres_rustls = "0.1.6"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring", "custom-provider"] }
webpki-roots = "1.0.9"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
incremental = false
